#?? ?? ??
server:
  port: 8000

# database ?? ??
spring:
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lol_matching?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1704
  thymeleaf:
    cache: false

# Spring data jpa ??
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
